### ISSUE TITLE
requires @vueuse/core when calling useLoader 

### ISSUE THREAD

**Issue by jangxyz** [Hebilicious/form-actions-nuxt#25]
### Environment

```
❯ node --version
v16.20.0

❯ npm ls
nuxt-app@ /home/projects/github-qgd4vt
+-- @hebilicious/form-actions-nuxt@0.1.0
+-- @nuxt/devtools@0.7.5
+-- @types/node@18.17.3
`-- nuxt@3.6.5
```

### Reproduction

I started with 1) a [fresh nuxt install](https://nuxt.com/docs/getting-started/installation#new-project) and 2) straight into [form-actions-nuxt install](https://github.com/Hebilicious/form-actions-nuxt#install), and 3) followed the steps on [Server Loaders section](https://github.com/Hebilicious/form-actions-nuxt#server-loaders).

Here is a screenshot:
<details>
<summary>Screenshot</summary>

<img width="1514" alt="image" src="https://github.com/Hebilicious/form-actions-nuxt/assets/52015/dc55a74c-8a91-402d-93bc-2452639ffeb5">

</details>
 
and a [stackblitz link](https://stackblitz.com/edit/github-qgd4vt?file=components%2FBooks.vue). Also confirmed in local environments as well.

### Describe the bug

The `useLoader` composable is importing `useThrottleFn` from @vueuse/core ([runtime/composables/useLoader.ts#L2](https://github.com/Hebilicious/form-actions-nuxt/blob/6aa2527cfc2d8d9a911839c75527d39c62c256eb/packages/form-actions-nuxt/src/runtime/composables/useLoader.ts#L2)), but for some reason the package is left out from the package.json file. 

Installing "@vueuse/core" on my hand did solve the issue, but I think it's better to be in the library's package file. Tried cloning the project and adding the package myself, and confirmed that it resolves the issue.

### Logs

```sh
<details>
<summary>Error log</summary>


[4:07:12 PM]  ERROR  Internal server error: Failed to resolve import "@vueuse/core" from "node_modules/.pnpm/@hebilicious+form-actions-nuxt@0.1.0_h3@1.7.1_nuxt@3.6.5_vite@4.4.9/node_modules/@hebilicious/form-actions-nuxt/dist/runtime/composables/useLoader.mjs?v=2e32783a". Does the file exist?
  Plugin: vite:import-analysis
  File: /Users/jangxyz/work/realdraw-2023/testing-form-actions-nuxt/default-install/node_modules/.pnpm/@hebilicious+form-actions-nuxt@0.1.0_h3@1.7.1_nuxt@3.6.5_vite@4.4.9/node_modules/@hebilicious/form-actions-nuxt/dist/runtime/composables/useLoader.mjs?v=2e32783a:3:32
  1  |  import { useFetch, useRoute } from '#app';
  2  |  import { ref } from "vue";
  3  |  import { useThrottleFn } from "@vueuse/core";
     |                                 ^
  4  |  import { NITRO_LOADER_PREFIX } from "../utils.mjs";
  5  |  const lastSubpath = (path) => path.split("/").pop();
      at formatError (file:///Users/jangxyz/work/realdraw-2023/testing-form-actions-nuxt/default-install/node_modules/.pnpm/vite@4.3.9_@types+node@18.17.1/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:42645:46)
      at TransformContext.error (file:///Users/jangxyz/work/realdraw-2023/testing-form-actions-nuxt/default-install/node_modules/.pnpm/vite@4.3.9_@types+node@18.17.1/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:42641:19)
      at normalizeUrl (file:///Users/jangxyz/work/realdraw-2023/testing-form-actions-nuxt/default-install/node_modules/.pnpm/vite@4.3.9_@types+node@18.17.1/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:40508:33)
      at async file:///Users/jangxyz/work/realdraw-2023/testing-form-actions-nuxt/default-install/node_modules/.pnpm/vite@4.3.9_@types+node@18.17.1/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:40651:47
      at async Promise.all (index 2)
      at async TransformContext.transform (file:///Users/jangxyz/work/realdraw-2023/testing-form-actions-nuxt/default-install/node_modules/.pnpm/vite@4.3.9_@types+node@18.17.1/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:40577:13)
      at async file:///Users/jangxyz/work/realdraw-2023/testing-form-actions-nuxt/default-install/node_modules/.pnpm/vite-plugin-inspect@0.7.35_@nuxt+kit@3.6.5_vite@4.4.9/node_modules/vite-plugin-inspect/dist/index.mjs:884:23
      at async Object.transform (file:///Users/jangxyz/work/realdraw-2023/testing-form-actions-nuxt/default-install/node_modules/.pnpm/vite@4.3.9_@types+node@18.17.1/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:42919:30)
      at async loadAndTransform (file:///Users/jangxyz/work/realdraw-2023/testing-form-actions-nuxt/default-install/node_modules/.pnpm/vite@4.3.9_@types+node@18.17.1/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:53385:29)
```

</details>
```

**Comment by Hebilicious** [comment]
Good catch, it should be in the dependencies of the module !
