### ISSUE TITLE
sendRedirect is not defined

### ISSUE THREAD

**Issue by aaronksaunders** [Hebilicious/form-actions-nuxt#49]
### Environment

node v18.16.0

### Reproduction

https://github.com/aaronksaunders/nuxt-starter-zbhadu-sendRedirect-issue

### Describe the bug

Getting error message when trying to build and document the process of getting a very basic login/register page working. I have worked through this far, other notes are documented in readme.md
```
[nuxt] [request error] [unhandled] [500] sendRedirect is not defined
  at respondWithRedirect (./node_modules/@hebilicious/form-actions-nuxt/dist/runtime/server/nitro.mjs:4:3)  
  at actionResponse (./node_modules/@hebilicious/form-actions-nuxt/dist/runtime/server/nitro.mjs:33:12)  
  at default (./server/actions/login.ts:24:1)  
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
  at async Object.handler (./node_modules/h3/dist/index.mjs:1630:19)  
  at async Server.toNodeHandle (./node_modules/h3/dist/index.mjs:1840:7)
```

**Comment by Hebilicious** [comment]
I was able to reproduce this bug. Pushing a fix now.
